BUG: Fix annotation logic build error
Two things here:
1 - Unused variable warning:
  Slicer4/Modules/Loadable/Annotations/Logic/vtkSlicerAnnotationModuleLogic.cxx:1998: warning: unused variable 'lengthUnit' [-Wunused-variable]

This is fixed by deleting the unused pointer

2 - ostringstream error:
  /Slicer4/Modules/Loadable/Annotations/Logic/vtkSlicerAnnotationModuleLogic.cxx:2018: error: no matching function for call to 'std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(double)'
  /Developer/SDKs/MacOSX10.6.sdk/usr/include/c++/4.2.1/sstream:433: note: candidates are: std::basic_ostringstream<_CharT, _Traits, _Alloc>::basic_ostringstream(const std::basic_string<_CharT, _Traits, _Alloc>&, std::_Ios_Openmode) [with _CharT = char, _Traits = std::char_traits<char>, _Alloc = std::allocator<char>]
  /Developer/SDKs/MacOSX10.6.sdk/usr/include/c++/4.2.1/sstream:412: note:                 std::basic_ostringstream<_CharT, _Traits, _Alloc>::basic_ostringstream(std::_Ios_Openmode) [with _CharT = char, _Traits = std::char_traits<char>, _Alloc = std::allocator<char>]
  /Developer/SDKs/MacOSX10.6.sdk/usr/include/c++/4.2.1/iosfwd:79: note:                 std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(const std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >&)
  /Slicer4/Modules/Loadable/Annotations/Logic/vtkSlicerAnnotationModuleLogic.cxx:2107: error: no matching function for call to 'vtkMRMLUnitNode::WrapValueWithPrefixAndSuffix(std::string)'
  /Slicer4/Libs/MRML/Core/vtkMRMLUnitNode.h:73: note: candidates are: std::string vtkMRMLUnitNode::WrapValueWithPrefixAndSuffix(std::string&)
  /Slicer4/Modules/Loadable/Annotations/Logic/vtkSlicerAnnotationModuleLogic.cxx:2128: error: no matching function for call to 'vtkMRMLUnitNode::WrapValueWithPrefixAndSuffix(std::string)'
  /Slicer4/Libs/MRML/Core/vtkMRMLUnitNode.h:73: note: candidates are: std::string vtkMRMLUnitNode::WrapValueWithPrefixAndSuffix(std::string&)

This is fized by using the ostringstream more properly.

See Issue #1694

git-svn-id: http://svn.slicer.org/Slicer4/trunk@22062 3bd1e089-480b-0410-8dfb-8563597acbee