COMP: Fix MacOSX RemoteIO build error by building against system CURL
Trying to build against our own version of curl end up in a mixing
of headers causing a build error:

// ---------------
In file included from /Developer/SDKs/MacOSX10.6.sdk/usr/include/curl/curl.h:43,
                 from /Users/kitware/Dashboards/Continuous/Slicer4/Libs/RemoteIO/vtkHTTPHandler.h:8,
                 from /Users/kitware/Dashboards/Continuous/Slicer4/Libs/RemoteIO/vtkHTTPHandler.cxx:1:
/Users/kitware/Dashboards/Continuous/Slicer4-build-64bits-QT4.8.5-PythonQt-With-Tcl-CLI-Release-continuous/curl-build/include/curl/curlbuild.h:151: error: 'socklen_t' does not name a type
In file included from /Developer/SDKs/MacOSX10.6.sdk/usr/include/curl/curl.h:44,
                 from /Users/kitware/Dashboards/Continuous/Slicer4/Libs/RemoteIO/vtkHTTPHandler.h:8,
                 from /Users/kitware/Dashboards/Continuous/Slicer4/Libs/RemoteIO/vtkHTTPHandler.cxx:1:
/Developer/SDKs/MacOSX10.6.sdk/usr/include/curl/curlrules.h:174: error: 'curl_socklen_t' was not declared in this scope
/Developer/SDKs/MacOSX10.6.sdk/usr/include/curl/curlrules.h:184: error: 'curl_socklen_t' was not declared in this scope
// ---------------

While not providing a definite explanation regarding the root cause of
the problem, we circumvent it by building against the system version
of the library.

See #1739

git-svn-id: http://svn.slicer.org/Slicer4/trunk@22728 3bd1e089-480b-0410-8dfb-8563597acbee